# Generated by Django 5.2.8 on 2026-02-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkietaSkorupy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_edycji', models.DateTimeField(auto_now=True)),
                ('data_wygasniecia', models.DateTimeField(blank=True, null=True)),
                ('czy_aktywna', models.BooleanField(default=True)),
                ('tworca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moje_ankiety', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
