# Generated by Django 5.2.8 on 2026-02-15 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skorupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł skorupy')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_wygasniecia', models.DateTimeField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skorupy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skorupa',
                'verbose_name_plural': 'Skorupy',
                'ordering': ['-data_utworzenia'],
            },
        ),
    ]
